version: '2'
services:

  nginx:
    build: nginx
    volumes:
      - ./app:/var/app
    ports:
      - 80:80
    environment:
      - PATH=/usr/local/openresty/bin:/usr/local/openresty/nginx/sbin:$PATH
